language: go

go:
  - 1.14
  - 1.15
  - 1.15.4
  - 1.15.6

services:
  - mongodb

before_script:
  - sudo mkdir /var/log/harvestccode && sudo touch /var/log/harvestccode/logifile
  - sudo chown travis /var/log/harvestccode/logifile

script:
  - make test

after_failure:
  - cat /var/log/harvestccode/logfile
