version: '3'
services:
  harvestccode:
    container_name: harvestccode
    build:
      context: .
      dockerfile: Dockerfile.hcc
    ports:
      - 8080:8080
    environment:
      - HCC_MONGO_HOST=mongo
    healthcheck:
      test: curl --fail -s http:localhost:8080/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      hcc:
        ipv4_address: 172.25.0.3
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.2
    networks:
      hcc:
        ipv4_address: 172.25.0.2

networks:
  hcc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16