version: '3'
services:
  mongo:
    image: mongo:4.4.2
    restart: always
    networks:
      hcc:
        ipv4_address: 172.25.0.2

  harvestccode:
    build:
      context: .
      dockerfile: Dockerfile.hcc
    restart: always
    expose:
      - 8080
    environment:
      - HCC_MONGO_URI=mongodb://mongo:27017
    healthcheck:
      test: curl --fail -s http://localhost:8080/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      hcc:
        ipv4_address: 172.25.0.3
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - harvestccode
    networks:
      hcc:
        ipv4_address: 172.25.0.4

networks:
  hcc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16