version: '3'
services:
  mongo:
    image: mongo:4.4.2
    networks:
      hcc:
        ipv4_address: 172.25.0.2

  harvestccode:
    build:
      context: .
      dockerfile: Dockerfile.hcc
    ports:
      - 8080:8080
    environment:
      - HCC_MONGO_URI=mongodb://mongo:27017
    healthcheck:
      test: curl --fail -s http://localhost:8080/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      hcc:
        ipv4_address: 172.25.0.3
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /usr/share/nginx/html
      - /etc/share/vhost.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - nginx

networks:
  hcc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16