name: Go linter

on:
  push:
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Setup Go v1.15.4
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'

    - name: Go linter
      run: make lint
