name: Go linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Go linter
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
