name: Publish testing Docker image

on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  push-to-registries:
    name: Push to registries
    runs-on: ubuntu-latest
    env:
      image-tag: harvestcore/harvestccode:latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub - Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: DockerHub - Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.image-tag }}

    - name: GitHub Registry - Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: GitHub Registry - Build and push image
      run: docker build . -f Dockerfile -t ghcr.io/${{ env.image-tag }} && docker push ghcr.io/${{ env.image-tag }}
