name: Tests

on:
  push:
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Setup Go v1.15.4
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'

    - name: Run mongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 4.4.2

    - name: Install deps
      run: cd src && go get ./...

    - name: Run tests
      run: cd src && go test ./... -v
