name: Tests

on:
  push:
    paths:
      - '.github/**'
      - 'src/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.15.4', '1.15.6']
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Run mongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 4.4.2

    - name: Run tests
      run: make test

    - name: Show log
      if: ${{ always() }}
      run: cat ./harvestccode.log
